### ISSUE TITLE
3895285

### ISSUE THREAD

**Issue by multiflat** [multiflat/tarotBlood#2]
https://github.com/ionic-team/ionic-unit-testing-example
https://leifwells.github.io/blog/2017-08-27-adding-testing-to-ionic-app/

에 따라서 ionic의 테스트 세팅을 하고 있으나, 몇 년 전 문서라 제대로 작동할지 모르겠음.

**Comment by multiflat** [comment]
다음과 같은 출력 후 작동하지 않음. ionic에서 TDD는 어려울 지도.

webpack was not included as a framework in karma configuration, setting this automatically...
Webpack bundling...
Webpack starts watching...
ValidationError: Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration.module.rules[1] should be one of these:
   ["..." | object { compiler?, dependency?, descriptionData?, enforce?, exclude?, generator?, include?, issuer?, issuerLayer?, layer?, loader?, mimetype?, oneOf?, options?, parser?, realResource?, resolve?, resource?, resourceFragment?, resourceQuery?, rules?, scheme?, sideEffects?, test?, type?, use? }, ...]
   -> A rule.
   Details:
    * configuration.module.rules[0] has an unknown property 'loaders'. These properties are valid:
      object { compiler?, dependency?, descriptionData?, enforce?, exclude?, generator?, include?, issuer?, issuerLayer?, layer?, loader?, mimetype?, oneOf?, options?, parser?, realResource?, resolve?, resource?, resourceFragment?, resourceQuery?, rules?, scheme?, sideEffects?, test?, type?, use? }
      -> A rule description with conditions and effects for modules.
    * configuration.module.rules[1] has an unknown property 'query'. These properties are valid:
      object { compiler?, dependency?, descriptionData?, enforce?, exclude?, generator?, include?, issuer?, issuerLayer?, layer?, loader?, mimetype?, oneOf?, options?, parser?, realResource?, resolve?, resource?, resourceFragment?, resourceQuery?, rules?, scheme?, sideEffects?, test?, type?, use? }
      -> A rule description with conditions and effects for modules.
    at validate (/Users/shin/TarotBlood/node_modules/webpack/node_modules/schema-utils/dist/validate.js:105:11)
    at validateSchema (/Users/shin/TarotBlood/node_modules/webpack/lib/validateSchema.js:78:2)
    at create (/Users/shin/TarotBlood/node_modules/webpack/lib/webpack.js:109:24)
    at webpack (/Users/shin/TarotBlood/node_modules/webpack/lib/webpack.js:135:47)
    at f (/Users/shin/TarotBlood/node_modules/webpack/lib/index.js:55:16)
    at /Users/shin/TarotBlood/node_modules/karma-webpack/lib/karma-webpack/controller.js:79:25
    at new Promise (<anonymous>)
    at KW_Controller._bundle (/Users/shin/TarotBlood/node_modules/karma-webpack/lib/karma-webpack/controller.js:76:12)
    at KW_Controller.bundle (/Users/shin/TarotBlood/node_modules/karma-webpack/lib/karma-webpack/controller.js:68:34)
    at processFile (/Users/shin/TarotBlood/node_modules/karma-webpack/lib/karma-webpack/preprocessor.js:87:22)

**Comment by multiflat** [comment]
ce08851에서 revert 처리.
